### ISSUE TITLE
Missing template for /admin/server

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#124]
Visiting the `/admin/server` page results in the following error: 

```
Error: Template server not found!

/var/www/shaarli/inc/rain.tpl.class.php268
#0 /var/www/shaarli/inc/rain.tpl.class.php(164): RainTPL->check_template('server')
#1 /var/www/shaarli/application/render/PageBuilder.php(253): RainTPL->draw('server', true)
#2 /var/www/shaarli/application/front/controller/visitor/ShaarliVisitorController.php(66): Shaarli\Render\PageBuilder->render('server', '')
#3 /var/www/shaarli/application/front/controller/admin/ServerController.php(65): Shaarli\Front\Controller\Visitor\ShaarliVisitorController->render('server')
#4 [internal function]: Shaarli\Front\Controller\Admin\ServerController->index(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /var/www/shaarli/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /var/www/shaarli/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#7 /var/www/shaarli/application/front/ShaarliMiddleware.php(55): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /var/www/shaarli/application/front/ShaarliAdminMiddleware.php(25): Shaarli\Front\ShaarliMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#9 [internal function]: Shaarli\Front\ShaarliAdminMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#10 /var/www/shaarli/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Array, Array)
#11 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#12 /var/www/shaarli/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#13 /var/www/shaarli/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/shaarli/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/shaarli/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /var/www/shaarli/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/shaarli/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/shaarli/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /var/www/shaarli/index.php(196): Slim\App->run(true)
#20 {main}
```

This page is reasonably new in Shaarli.

**Comment by kalvn** [comment]
This is normal, I didn't build the page yet. I'm quite late compared to Shaarli, I'll take some time to work on catching up soon.

**Comment by kalvn** [comment]
The page is available now on the support-v012 branch :)

**Comment by immanuelfodor** [comment]
Wow, it looks great, nice job with the build!
