### ISSUE TITLE
Shaarli v0.14.0 support

### ISSUE THREAD

**Issue by immanuelfodor** [kalvn/Shaarli-Material#136]
Shaarli has recently released [v0.14.0](https://github.com/shaarli/Shaarli/releases/tag/v0.14.0). Is it supported by the Material theme? 
If yes, could you please bump the tested & validated version?

**Comment by immanuelfodor** [comment]
I rebuilt mine and observed the following problems:

- The newly listed [upload image plugin](https://github.com/meerkatzenwildschein/shaarli-image-upload) from the Shaarli docs is rendered badly :cry: 
![image](https://github.com/user-attachments/assets/d7d09b85-39ff-42ed-9dc4-d95346edbd9c)

- The theme build fails on `alpine/git` builder image with latest node and npm. I needed to use a 2 year-old image tag to make it work again:


<details>
<summary>Latest builder image logs (fail)</summary>

```
Step 1/28 : FROM alpine/git as builder

latest: Pulling from alpine/git

38a8310d387e: Pulling fs layer

1b2182dafcd1: Pulling fs layer

486a52a85c5a: Pulling fs layer

486a52a85c5a: Verifying Checksum

486a52a85c5a: Download complete

38a8310d387e: Verifying Checksum

38a8310d387e: Download complete

38a8310d387e: Pull complete

1b2182dafcd1: Verifying Checksum

1b2182dafcd1: Download complete

1b2182dafcd1: Pull complete

486a52a85c5a: Pull complete

Digest: sha256:39ac44ff6c6f659ee55eedd221a6b7e4cdfcf9d17ea2be024f588c3ddcd3ce7d

Status: Downloaded newer image for alpine/git:latest

 ---> 7c13633fee18

Step 2/28 : RUN apk add --update --no-cache npm

 ---> Running in 73c2b388bcfa

fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/main/x86_64/APKINDEX.tar.gz

fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/community/x86_64/APKINDEX.tar.gz

(1/10) Installing ca-certificates (20241010-r0)

(2/10) Installing libgcc (14.2.0-r4)

(3/10) Installing libstdc++ (14.2.0-r4)

(4/10) Installing ada-libs (2.9.2-r1)

(5/10) Installing icu-data-en (74.2-r0)

Executing icu-data-en-74.2-r0.post-install

*

* If you need ICU with non-English locales and legacy charset support, install

* package icu-data-full.

*

(6/10) Installing icu-libs (74.2-r0)

(7/10) Installing simdjson (3.10.1-r0)

(8/10) Installing simdutf (5.6.3-r0)

(9/10) Installing nodejs (22.11.0-r0)

(10/10) Installing npm (10.9.1-r0)

Executing busybox-1.37.0-r8.trigger

Executing ca-certificates-20241010-r0.trigger

OK: 150 MiB in 75 packages

Removing intermediate container 73c2b388bcfa

 ---> b9bfd886b387

Step 3/28 : WORKDIR /tpl

 ---> Running in 706a7e836d14

Removing intermediate container 706a7e836d14

 ---> d0c5c1a68fe7

Step 4/28 : RUN set -x     && git clone https://github.com/kalvn/Shaarli-Material.git material     && cd material     && git checkout support-v0.12.2     && npm install --unsafe-perm node-sass     && npm install     && npm run-script build

 ---> Running in 12f478dec410

+ git clone https://github.com/kalvn/Shaarli-Material.git material

Cloning into 'material'...

+ cd material

+ git checkout support-v0.12.2

branch 'support-v0.12.2' set up to track 'origin/support-v0.12.2'.

Switched to a new branch 'support-v0.12.2'

+ npm install --unsafe-perm node-sass

npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.

npm warn deprecated npmlog@6.0.2: This package is no longer supported.

npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

npm warn deprecated gauge@4.0.4: This package is no longer supported.

npm warn deprecated eslint-plugin-standard@5.0.0: standard 16.0.0 and eslint-config-standard 16.0.0 no longer require the eslint-plugin-standard package. You can remove it from your dependencies with 'npm rm eslint-plugin-standard'. More info here: https://github.com/standard/standard/issues/1316

npm warn deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

npm warn deprecated salvattore@1.0.9: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

npm warn deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported

npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

npm warn deprecated node-sass@9.0.0: Node Sass is no longer supported. Please use `sass` or `sass-embedded` instead.

npm error code 1

npm error path /tpl/material/node_modules/node-sass

npm error command failed

npm error command sh -c node scripts/build.js

npm error Binary found at /tpl/material/node_modules/node-sass/vendor/linux_musl-x64-127/binding.node

npm error Testing binary

npm error Binary has a problem: Error: Error loading shared library /tpl/material/node_modules/node-sass/vendor/linux_musl-x64-127/binding.node: Exec format error

npm error     at Object..node (node:internal/modules/cjs/loader:1715:18)

npm error     at Module.load (node:internal/modules/cjs/loader:1318:32)

npm error     at Function._load (node:internal/modules/cjs/loader:1128:12)

npm error     at TracingChannel.traceSync (node:diagnostics_channel:315:14)

npm error     at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)

npm error     at Module.require (node:internal/modules/cjs/loader:1340:12)

npm error     at require (node:internal/modules/helpers:141:16)

npm error     at module.exports (/tpl/material/node_modules/node-sass/lib/binding.js:19:10)

npm error     at Object.<anonymous> (/tpl/material/node_modules/node-sass/lib/index.js:13:35)

npm error     at Module._compile (node:internal/modules/cjs/loader:1546:14) {

npm error   code: 'ERR_DLOPEN_FAILED'

npm error }

npm error Building the binary locally

npm error Building: /usr/bin/node /tpl/material/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=

npm error gyp info it worked if it ends with ok

npm error gyp verb cli [

npm error gyp verb cli   '/usr/bin/node',

npm error gyp verb cli   '/tpl/material/node_modules/node-gyp/bin/node-gyp.js',

npm error gyp verb cli   'rebuild',

npm error gyp verb cli   '--verbose',

npm error gyp verb cli   '--libsass_ext=',

npm error gyp verb cli   '--libsass_cflags=',

npm error gyp verb cli   '--libsass_ldflags=',

npm error gyp verb cli   '--libsass_library='

npm error gyp verb cli ]

npm error gyp info using node-gyp@8.4.1

npm error gyp info using node@22.11.0 | linux | x64

npm error gyp verb command rebuild []

npm error gyp verb command clean []

npm error gyp verb clean removing "build" directory

npm error gyp verb command configure []

npm error gyp verb find Python checking Python explicitly set from command line or npm configuration

npm error gyp verb find Python - "--python=" or "npm config get python" is "/usr/bin/python3"

npm error gyp verb find Python - executing "/usr/bin/python3" to get executable path

npm error (node:59) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.

npm error (Use `node --trace-deprecation ...` to show where the warning was created)

npm error gyp verb find Python - "/usr/bin/python3" is not in PATH or produced an error

npm error gyp verb find Python Python is not set from environment variable PYTHON

npm error gyp verb find Python checking if "python3" can be used

npm error gyp verb find Python - executing "python3" to get executable path

npm error gyp verb find Python - "python3" is not in PATH or produced an error

npm error gyp verb find Python checking if "python" can be used

npm error gyp verb find Python - executing "python" to get executable path

npm error gyp verb find Python - "python" is not in PATH or produced an error

npm error gyp ERR! find Python 

npm error gyp ERR! find Python checking Python explicitly set from command line or npm configuration

npm error gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"

npm error gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error

npm error gyp ERR! find Python Python is not set from environment variable PYTHON

npm error gyp ERR! find Python checking if "python3" can be used

npm error gyp ERR! find Python - "python3" is not in PATH or produced an error

npm error gyp ERR! find Python checking if "python" can be used

npm error gyp ERR! find Python - "python" is not in PATH or produced an error

npm error gyp ERR! find Python 

npm error gyp ERR! find Python **********************************************************

npm error gyp ERR! find Python You need to install the latest version of Python.

npm error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,

npm error gyp ERR! find Python you can try one of the following options:

npm error gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"

npm error gyp ERR! find Python   (accepted by both node-gyp and npm)

npm error gyp ERR! find Python - Set the environment variable PYTHON

npm error gyp ERR! find Python - Set the npm configuration variable python:

npm error gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"

npm error gyp ERR! find Python For more information consult the documentation at:

npm error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation

npm error gyp ERR! find Python **********************************************************

npm error gyp ERR! find Python 

npm error gyp ERR! configure error 

npm error gyp ERR! stack Error: Could not find any Python installation to use

npm error gyp ERR! stack     at PythonFinder.fail (/tpl/material/node_modules/node-gyp/lib/find-python.js:330:47)

npm error gyp ERR! stack     at PythonFinder.runChecks (/tpl/material/node_modules/node-gyp/lib/find-python.js:159:21)

npm error gyp ERR! stack     at PythonFinder.<anonymous> (/tpl/material/node_modules/node-gyp/lib/find-python.js:202:16)

npm error gyp ERR! stack     at PythonFinder.execFileCallback (/tpl/material/node_modules/node-gyp/lib/find-python.js:294:16)

npm error gyp ERR! stack     at exithandler (node:child_process:427:5)

npm error gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)

npm error gyp ERR! stack     at ChildProcess.emit (node:events:518:28)

npm error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)

npm error gyp ERR! stack     at onErrorNT (node:internal/child_process:483:16)

npm error gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

npm error gyp ERR! System Linux 6.8.0-51-generic

npm error gyp ERR! command "/usr/bin/node" "/tpl/material/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="

npm error gyp ERR! cwd /tpl/material/node_modules/node-sass

npm error gyp ERR! node -v v22.11.0

npm error gyp ERR! node-gyp -v v8.4.1

npm error gyp ERR! not ok 

npm error Build failed with error code: 1

npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-19T10_56_27_583Z-debug-0.log

The command '/bin/sh -c set -x     && git clone https://github.com/kalvn/Shaarli-Material.git material     && cd material     && git checkout support-v0.12.2     && npm install --unsafe-perm node-sass     && npm install     && npm run-script build' returned a non-zero code: 1

exit status 1
```

</details>



<details>
<summary>Logs with alpine/git:2.36.3 (works with old node but many warns)</summary>

```
Step 1/28 : FROM alpine/git:2.36.3 as builder

2.36.3: Pulling from alpine/git

ca7dd9ec2225: Pulling fs layer

eb878e0a08e4: Pulling fs layer

b4f093b99828: Pulling fs layer

ca7dd9ec2225: Verifying Checksum

ca7dd9ec2225: Download complete

b4f093b99828: Verifying Checksum

b4f093b99828: Download complete

ca7dd9ec2225: Pull complete

eb878e0a08e4: Verifying Checksum

eb878e0a08e4: Download complete

eb878e0a08e4: Pull complete

b4f093b99828: Pull complete

Digest: sha256:66b210a97bc07bfd4019826bcd13a488b371a6cbe2630a4b37d23275658bd3f2

Status: Downloaded newer image for alpine/git:2.36.3

 ---> 22d84a66cda4

Step 2/28 : RUN apk add --update --no-cache npm

 ---> Running in 3d9a69f59929

fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz

fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz

(1/8) Installing c-ares (1.19.1-r1)

(2/8) Installing libgcc (11.2.1_git20220219-r2)

(3/8) Installing icu-data-en (71.1-r2)

Executing icu-data-en-71.1-r2.post-install

*

* If you need ICU with non-English locales and legacy charset support, install

* package icu-data-full.

*

(4/8) Installing libstdc++ (11.2.1_git20220219-r2)

(5/8) Installing icu-libs (71.1-r2)

(6/8) Installing libuv (1.44.1-r0)

(7/8) Installing nodejs-current (18.9.1-r0)

(8/8) Installing npm (8.10.0-r0)

Executing busybox-1.35.0-r17.trigger

OK: 100 MiB in 51 packages

Removing intermediate container 3d9a69f59929

 ---> 26db0880969b

Step 3/28 : WORKDIR /tpl

 ---> Running in 9270d5d78bfc

Removing intermediate container 9270d5d78bfc

 ---> a67721cd5743

Step 4/28 : RUN set -x     && git clone https://github.com/kalvn/Shaarli-Material.git material     && cd material     && git checkout support-v0.12.2     && npm install --unsafe-perm node-sass     && npm install     && npm run-script build

 ---> Running in 268b8f055181

+ git clone https://github.com/kalvn/Shaarli-Material.git material

Cloning into 'material'...

+ cd material

+ git checkout support-v0.12.2

branch 'support-v0.12.2' set up to track 'origin/support-v0.12.2'.

Switched to a new branch 'support-v0.12.2'

+ npm install --unsafe-perm node-sass

npm WARN deprecated are-we-there-yet@3.0.1: This package is no longer supported.

npm WARN deprecated npmlog@6.0.2: This package is no longer supported.

npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

npm WARN deprecated gauge@4.0.4: This package is no longer supported.

npm WARN deprecated eslint-plugin-standard@5.0.0: standard 16.0.0 and eslint-config-standard 16.0.0 no longer require the eslint-plugin-standard package. You can remove it from your dependencies with 'npm rm eslint-plugin-standard'. More info here: https://github.com/standard/standard/issues/1316

npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

npm WARN deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported

npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

npm WARN deprecated salvattore@1.0.9: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

npm WARN deprecated node-sass@9.0.0: Node Sass is no longer supported. Please use `sass` or `sass-embedded` instead.


added 623 packages, and audited 624 packages in 25s


107 packages are looking for funding

  run `npm fund` for details


11 vulnerabilities (6 moderate, 4 high, 1 critical)


To address issues that do not require attention, run:

  npm audit fix


To address all issues (including breaking changes), run:

  npm audit fix --force


Run `npm audit` for details.

+ npm install


up to date, audited 624 packages in 2s


107 packages are looking for funding

  run `npm fund` for details


11 vulnerabilities (6 moderate, 4 high, 1 critical)


To address issues that do not require attention, run:

  npm audit fix


To address all issues (including breaking changes), run:

  npm audit fix --force


Run `npm audit` for details.

+ npm run-script build


> shaarlimaterial@0.12.1 build

> cross-env NODE_ENV=production rollup -c



src/js/main.js → material/dist/bundle.js...

Browserslist: caniuse-lite is outdated. Please run:

  npx update-browserslist-db@latest

  Why you should do it regularly: https://github.com/browserslist/update-db#readme

created material/dist/bundle.js in 21.3s

Removing intermediate container 268b8f055181

 ---> b7eb71994f24

...
```

</details>

Builder dockerfile for reference:

```
FROM alpine/git:2.36.3 as builder

RUN apk add --update --no-cache npm

WORKDIR /tpl
RUN set -x \
    && git clone https://github.com/kalvn/Shaarli-Material.git material \
    && cd material \
    && git checkout support-v0.12.2 \
    && npm install --unsafe-perm node-sass \
    && npm install \
    && npm run-script build
```

**Comment by immanuelfodor** [comment]
We managed to fix the image upload issue with the plugin author by updating the plugin code, now it looks okay:

![image](https://github.com/user-attachments/assets/34ce1071-6999-4435-ab24-832d2d84281a)

**Comment by kalvn** [comment]
I tested Shaarli v0.14 super quickly in local with the theme and didn't encounter any problem.

But I did not make extensive tests. I'll do it in the coming weeks and will update the README accordingly.

**Comment by kalvn** [comment]
I've started branch **support-v0.14.0** and updated all JavaScript dependencies, which should make the build easier when using modern versions of Node. I have to stop for now but will go over the whole application again in the coming days to validate that everything works fine.

Just be informed that I removed a lot of legacy tools to support very old browser. It shouldn't be an issue, but if you test the theme in a production environment, please be aware.

**Comment by kalvn** [comment]
I just released https://github.com/kalvn/Shaarli-Material/releases/tag/v0.14.0 :)

There were almost only changes to Shaarli internals between v0.13.0 and v0.14.0 so pretty straight-forward. I'll deploy it on my instance to do further testing, but I'm quite confident it works fine.

**Comment by immanuelfodor** [comment]
LGTM, perfect Christmas gift! :partying_face: I'm closing the issue, thank you!

Note: I could go up to an Alpine v3.20 based builder image that contains Node v20 but needed to explicitly use the `nodejs` package as the implicit `nodejs-current` dependency of `npm` would pull Node v21 that fails to build. This Alpine image is 24 days old as of today, so it's a great achievement. Thank you! Dockerfile for reference if anybody needs it:

```Dockerfile
FROM alpine/git:2.45.2 as builder

RUN apk add --update --no-cache nodejs npm

WORKDIR /tpl
RUN set -x \
    && git clone https://github.com/kalvn/Shaarli-Material.git material \
    && cd material \
    && git checkout support-v0.14.0 \
    && npm install --unsafe-perm node-sass \
    && npm install \
    && npm run-script build
```
